#!/usr/bin/env bash

# Bash Script for getting your current Linux Kernel's Codename from the kernel source makefile.
# https://gist.github.com/paulbdavis/4744581

pattern="NAME\s\?=\s\?"
kernelVersion=$(uname -r | sed "s/-.*//g")
# strip trailing .0 version, since the git tags on kernel.org do not have them
kernelVersion=${kernelVersion/%".0"/}

cacheDir="/var/tmp/kernel-codename"
cacheFile="$cacheDir/$USER"
mkdir -p "$cacheDir"

if [[ -f "$cacheFile" ]]; then
    cache=$(cat $cacheFile)
    cachedVersion=$(expr "$cache" : '\([0-9.]*\)')
    cachedName=$(expr "$cache" : '.*@\([-A-Za-z ]*\)')
    # echo "v:$cachedVersion n:$cachedName"
    if [[ "$cachedVersion" = "$kernelVersion" ]]
    then
        kernelCodename="$cachedName"
    fi
fi

if [[ -z "$kernelCodename" ]]; then
    url="https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/plain/Makefile?id=refs/tags/v${kernelVersion}"
    kernelCodename=$(grep $pattern <<<"$(curl -Ls "$url")" | sed "s/$pattern//g")
fi

echo "$kernelVersion@$kernelCodename" > "$cacheFile"

if [[ "$1" == "-a" ]]
then
    echo "$kernelCodename ($kernelVersion)"
else
    echo "$kernelCodename"
fi
